### ISSUE TITLE
Using HDFS connector with latest OCI SDK

### ISSUE THREAD

**Issue by janotav** [oracle/oci-hdfs-connector#13]
I'm trying to use the latest version of the oci-hdfs connector. 

If I use it through dependency on oci-hdfs-full and I'm getting following exception:

`
java.lang.NoSuchMethodError: com.oracle.bmc.objectstorage.model.Bucket.getApproximateSize()Ljava/lang/Long;
`

This is probably caused by the fact that another part of the project consumes more recent version OCI SDK (1.4.0) which is not compatible and clashes.  Any chance of releasing oci-hdfs-full with up-to-date OCI SDK? 

Trying to depend on oci-hdfs instead I'm getting:

```
Caused by: java.lang.NoClassDefFoundError: jersey/repackaged/com/google/common/base/Function
	at shaded.oracle.org.glassfish.jersey.client.ClientConfig$State.<init>(ClientConfig.java:150)
	at shaded.oracle.org.glassfish.jersey.client.ClientConfig.<init>(ClientConfig.java:468)
	at shaded.oracle.org.glassfish.jersey.client.JerseyClientBuilder.<init>
.....
	at shaded.oracle.javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:86)
	at com.oracle.bmc.http.internal.RestClientFactory.createClient(RestClientFactory.java:154)
	at com.oracle.bmc.http.internal.RestClientFactory.create(RestClientFactory.java:141)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:202)
```

Is additional dependency needed? Which?

**Comment by sumitkdey** [comment]
Hi @janotav, The latest release of the HDFS connector 2.7.7.2 has been updated to use the Java SDK version 1.4.2.
