### ISSUE TITLE
Invalid host:port authority in Kerberized cluster

### ISSUE THREAD

**Issue by imw** [oracle/oci-hdfs-connector#4]
It appears that this connector does not work in clusters where Kerberos authentication is enabled. Failure trace (sensitive details changed) is:
`java.lang.IllegalArgumentException: Does not contain a valid host:port authority: bucket@namespace
        at org.apache.hadoop.net.NetUtils.createSocketAddr(NetUtils.java:212)
        at org.apache.hadoop.net.NetUtils.createSocketAddr(NetUtils.java:164)
        at org.apache.hadoop.security.SecurityUtil.buildDTServiceName(SecurityUtil.java:290)
        at org.apache.hadoop.fs.FileSystem.getCanonicalServiceName(FileSystem.java:318)
        at org.apache.hadoop.fs.FileSystem.collectDelegationTokens(FileSystem.java:540)
        at org.apache.hadoop.fs.FileSystem.addDelegationTokens(FileSystem.java:524)
        at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:140)
        at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:100)
        at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodes(TokenCache.java:80)
        at org.apache.hadoop.tools.mapred.CopyOutputFormat.checkOutputSpecs(CopyOutputFormat.java:124)
        at org.apache.hadoop.mapreduce.JobSubmitter.checkSpecs(JobSubmitter.java:270)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:143)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1307)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1304)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1304)
        at org.apache.hadoop.tools.DistCp.execute(DistCp.java:182)
        at org.apache.hadoop.tools.DistCp.run(DistCp.java:143)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.tools.DistCp.main(DistCp.java:493)
`
This occurs just after the BmcFilesystem initialization. It seems plausible that overriding the getCanonicalServiceName method from org.apache.hadoop.fs.FileSystem, in order to return a null value could be a potential fix.

To reproduce: Use connector on cluster with hadoop.security.authentication = kerberos

**Comment by imw** [comment]
@sumitkdey Sure. You can reach me at isaac.wilder@ultratendency.com - let me know what I can do.

**Comment by sumitkdey** [comment]
@imw Thanks, I sent you a couple of mails but have not heard back. Could you please check your junk folder?

**Comment by sumitkdey** [comment]
This is fixed in release 2.7.2.1
